# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'Sharer' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Sharer
  pod 'Firebase', '>= 2.5.1'

  target 'SharerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SharerUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
