# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'Sharer' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Sharer
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'Firebase/Auth'
  pod 'Firebase/Storage'
  pod "BSImagePicker", "~> 2.3"
  pod 'Material', '~> 1.42.7’
  pod 'FoldingCell', '~> 0.7.2'
  pod 'Rosefire', :git => 'https://ada.csse.rose-hulman.edu/rosefire/ios-sdk.git', :tag => '2.1.0'

  pod 'GoogleSignIn'
  target 'SharerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SharerUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
